namespace Domain.Numbers;

public static class NumberConstants
{
    public static readonly IList<Number> EuropeanNumbers = new List<Number>
    {
        new("0", NumberColor.Green),
        new("32", NumberColor.Red),
        new("15", NumberColor.Black),
        new("19", NumberColor.Red),
        new("4", NumberColor.Black),
        new("21", NumberColor.Red),
        new("2", NumberColor.Black),
        new("25", NumberColor.Red),
        new("17", NumberColor.Black),
        new("34", NumberColor.Red),
        new("6", NumberColor.Black),
        new("27", NumberColor.Red),
        new("13", NumberColor.Black),
        new("36", NumberColor.Red),
        new("11", NumberColor.Black),
        new("30", NumberColor.Red),
        new("8", NumberColor.Black),
        new("23", NumberColor.Red),
        new("10", NumberColor.Black),
        new("5", NumberColor.Red),
        new("24", NumberColor.Black),
        new("16", NumberColor.Red),
        new("33", NumberColor.Black),
        new("1", NumberColor.Red),
        new("20", NumberColor.Black),
        new("14", NumberColor.Red),
        new("31", NumberColor.Black),
        new("9", NumberColor.Red),
        new("22", NumberColor.Black),
        new("18", NumberColor.Red),
        new("29", NumberColor.Black),
        new("7", NumberColor.Red),
        new("28", NumberColor.Black),
        new("12", NumberColor.Red),
        new("35", NumberColor.Black),
        new("3", NumberColor.Red),
        new("26", NumberColor.Black)
    };

    public static readonly IList<Number> AmericanNumbers = new List<Number>
    {
        new("0", NumberColor.Green),
        new("28", NumberColor.Black),
        new("9", NumberColor.Red),
        new("26", NumberColor.Black),
        new("30", NumberColor.Red),
        new("11", NumberColor.Black),
        new("7", NumberColor.Red),
        new("20", NumberColor.Black),
        new("32", NumberColor.Red),
        new("17", NumberColor.Black),
        new("5", NumberColor.Red),
        new("22", NumberColor.Black),
        new("34", NumberColor.Red),
        new("15", NumberColor.Black),
        new("3", NumberColor.Red),
        new("24", NumberColor.Black),
        new("36", NumberColor.Red),
        new("13", NumberColor.Black),
        new("1", NumberColor.Red),
        new("00", NumberColor.Green),
        new("27", NumberColor.Red),
        new("10", NumberColor.Black),
        new("25", NumberColor.Red),
        new("29", NumberColor.Black),
        new("12", NumberColor.Red),
        new("8", NumberColor.Black),
        new("19", NumberColor.Red),
        new("31", NumberColor.Black),
        new("18", NumberColor.Red),
        new("6", NumberColor.Black),
        new("21", NumberColor.Red),
        new("33", NumberColor.Black),
        new("16", NumberColor.Red),
        new("4", NumberColor.Black),
        new("23", NumberColor.Red),
        new("35", NumberColor.Black),
        new("14", NumberColor.Red),
        new("2", NumberColor.Black)
    };
}